config/routes.rb
Rails.application.routes.draw do
  resources :stats
  get 'metrics' => "stats#metrics", as: :metrics
  
  root 'static#test'

end

app/models/stat.rb
class Stat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def test
  end

  def test2
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]

  # GET /stats
  # GET /stats.json
  def index
    @stats = Stat.all
  end

  # GET /stats/1
  # GET /stats/1.json
  def show
  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render :show, status: :created, location: @stat }
      else
        format.html { render :new }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @stat }
      else
        format.html { render :edit }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url, notice: 'Stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def metrics
    if params[:metric] && params[:value]
      @stat = Stat.new(stat_params)
      Rails.logger.info("Stat Saved.") if @stat.save  
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
      params.permit(:metric, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DtfSample</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stats/_form.html.erb
<%= form_for(@stat) do |f| %>
  <% if @stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
      <% @stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :metric %><br>
    <%= f.text_field :metric %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing Stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

app/views/stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stats</h1>

<table>
  <thead>
    <tr>
      <th>Metric</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.metric %></td>
        <td><%= stat.value %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat', new_stat_path %>

app/views/stats/new.html.erb
<h1>New Stat</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Metric:</strong>
  <%= @stat.metric %>
</p>

<p>
  <strong>Value:</strong>
  <%= @stat.value %>
</p>

<%= link_to 'Edit', edit_stat_path(@stat) %> |
<%= link_to 'Back', stats_path %>